In [1]:
import numpy as np

In [6]:
np.NaN

nan

In [7]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
a[2]

array([ 9, 10, 11, 12])

In [17]:
np.array([[0,0,0],
        [1,1,1]])

array([[0, 0, 0],
       [1, 1, 1]])

## Creating Array

In [18]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [20]:
np.array(6)

array(6)

In [21]:
np.empty(6)

array([0., 0., 0., 0., 0., 0.])

In [22]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [23]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [24]:
np.arange(-2,-100,-5)

array([ -2,  -7, -12, -17, -22, -27, -32, -37, -42, -47, -52, -57, -62,
       -67, -72, -77, -82, -87, -92, -97])

In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2])

In [28]:
np.delete(arr, [1])

array([1, 3, 4, 5, 6, 7, 8, 9])

In [31]:
b = np.array([3,2,1,4,5,6,7,8,9])
b

array([3, 2, 1, 4, 5, 6, 7, 8, 9])

In [33]:
np.sort(b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Shape and Size

In [35]:
array_example = np.array([[[0,1,2,3],
                         [4,5,6,7]],
                        
                        [[0,1,2,3],
                        [4,5,6,7]],
                        
                          [[0,1,2,3],
                          [4,5,6,7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [36]:
array_example.ndim

3

In [37]:
array_example.size

24

In [38]:
array_example.shape

(3, 2, 4)

In [42]:
arr_one = np.array([[1,2,3,4,5]])
arr_one

array([[1, 2, 3, 4, 5]])

In [43]:
arr_one.ndim

2

In [44]:
arr_one.size

5

In [45]:
arr_one.shape

(1, 5)

## Reshape

In [55]:
c = np.arange(6)

print(c)

[0 1 2 3 4 5]


In [56]:
c = c.reshape(3,2)

print(c)

[[0 1]
 [2 3]
 [4 5]]


In [57]:
c.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

## Convert 1D to 2D

In [58]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [59]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [60]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [64]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [65]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [66]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

## Indexing and Slicing

In [67]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [68]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [70]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [71]:
divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [72]:
c = a[(a>2)&(a<11)]

print(c)

[ 3  4  5  6  7  8  9 10]


## Creating Array from Existing Data

In [73]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [74]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [76]:
a_1 = np.array([[1,1],
              [2,2]])

a_2 = np.array([[3,3],
               [4,4]])

np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [77]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
                    [13,14,15,16,17,18,19,20,21,22,23,24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [78]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [79]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [80]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [81]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Basic Array Operations

In [82]:
a = np.array([1,2,3,4])

a.sum()

10

In [83]:
b = np.array([[1,1],[2,2]])
b

array([[1, 1],
       [2, 2]])

In [85]:
b.sum(axis=0)

array([3, 3])

In [86]:
b.sum(axis=1)

array([2, 4])

In [87]:
data = np.array([1,2])
data

array([1, 2])

In [88]:
ones = np.ones(2)
ones

array([1., 1.])

In [89]:
data + ones

array([2., 3.])

In [92]:
data * data

array([1, 4])

In [93]:
data/data

array([1., 1.])

## Broadcasting

In [94]:
data *2

array([2, 4])

In [104]:
A = np.array([[0.45, 0.17, 0.34, 0.55],
             [0.54, 0.05, 0.40, 0.56],
             [0.12, 0.82, 0.26, 0.57]])

print(A)

[[0.45 0.17 0.34 0.55]
 [0.54 0.05 0.4  0.56]
 [0.12 0.82 0.26 0.57]]


In [105]:
A.sum()

4.830000000000001

In [106]:
A.min()

0.05

In [107]:
A.min(axis=0)

array([0.12, 0.05, 0.26, 0.55])

In [108]:
A.max()

0.82

In [110]:
A.max(axis=1)

array([0.55, 0.56, 0.82])

In [111]:
A.std()

0.21455865553891473

## Matrices

In [112]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [114]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.0603805  0.66833199]
 [0.10483929 0.10412995]
 [0.35397717 0.34911125]]


## Matrix Arithmetic

In [115]:
data = np.array([[1,2],[3,4]])
print(data)

[[1 2]
 [3 4]]


In [116]:
ones = np.ones([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [117]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [120]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [121]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


## Dot Product

In [122]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8],[9,10],[11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [123]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

## Matrix Indexing

In [124]:
data = np.array([[1,2],[3,4],[5,6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0:1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
[[1 2]]
[[3 4]
 [5 6]]
[2 4]


## Matrix Aggregation

In [125]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [126]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [127]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


## Transposing and Reshaping

In [128]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [129]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [130]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [131]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [132]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


## N-Dimensional Array

In [134]:
ndarr = np.array([[[1,2],[3,4]],
                    [[5,6],[7,8]]])
                    
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [135]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [136]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [137]:
print(np.random.random((4,3,2)))

[[[0.37184565 0.03081739]
  [0.93485641 0.39262129]
  [0.06486575 0.01720488]]

 [[0.96847665 0.53684475]
  [0.57912765 0.31035301]
  [0.88432447 0.20779227]]

 [[0.51669057 0.02905593]
  [0.37722147 0.25957788]
  [0.4890438  0.24846233]]

 [[0.8962249  0.49271498]
  [0.75892387 0.93286429]
  [0.17046927 0.40344486]]]


## Flatten N-Dimensional Array

In [138]:
arrflat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [139]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Working with Math Formulas

In [159]:
error = (1/n) * np.sum(np.square(observed - prediction))